### ISSUE TITLE
Location is "None" for many validators

### ISSUE THREAD

**Issue by dakk** [w3f/1k-validators-be#2569]
Since some days, the location value for many validator is None, both on polkadot and kusama.

- 127 over 486 validators on Polkadot
- 456 validators on Kusama

**Comment by wpank** [comment]
This should have been resolved with the last v3.0.12 deployment, although needed to remove those entries in the db. This should be resolved now. Feel free to re-open if it's not.

**Comment by lobis** [comment]
@wpank sorry if this is not the right place to post this, but atleast on https://telemetry.polkadot.io/ location appears to be broken. In particular my validators don't have a location. I believe this is also causing my location / region score to drop since it's not being properly reported. Is there something I need to do on my end?
