### ISSUE TITLE
Polkadot Staking Dashboard (staking.polkadot.network) and Polkadot.js can support decentralization of Validators much better

### ISSUE THREAD

**Issue by GlobalSG** [w3f/1k-validators-be#2572]
**WHAT'S HAPPENING?**

According to[ Polkadot Wiki ](https://wiki.polkadot.network/docs/thousand-validators), 1KV Program serves two major purposes:

**1.Give validators a structured on-ramp to join the active set of validators on Kusama and Polkadot
2.Further decentralize the validator active set.**
Now it is solving only p.1 - Give validators a structured on-ramp to join the active set, 
**but not fit - p.2 - decentralize the validator active set.** 

I am Alex PromoTeam , one of the first Polkadot Ambassadors, contributing to the ecosystem more than 4 years. I started a lot of initiatives and projects across the ecosystem, such as Parachain News https://twitter.com/DotParachains PromoTeam https://twitter.com/PromoTeamPD , I started Web3 community from the scratch in Central Asia, and developing and supporting Russian speaking community as Ambassador for more than 4 years and doing many other things in Polkadot ecosystem.

**I have Polkadot and Kusama Validator, and part of 1KV for more than 2 years. And I still don't have full organic stake nomination.**

**Maybe, just maybe,  its not something wrong with me and other 1KV Validators but interface of Polkadot.js and Staking Dashboard, which preference those who are already in Active list, but not who are mostly in Waiting list.**

Here is my Validator, hardware is good and unique location, its hard to make validator at this location by the way, and much more expensive then Europe or US.
PromoTeam | Web3 Uzbekistan 12BkPLskXyXrHhktrinLxVFkPzzvCzCyVCaqHkUEoxMwSzeq

**THE PROBLEM**

**Polkadot Staking Dashboard (staking.polkadot.network) and Polkadot.js can support decentralization of Validators much better.**

Algorithm that recommend validators for new stakers not works according the initial idea of decentralization and efficiency . It recommends mostly big networks of multi - validators - P2P, Jaco, Zug Capital, Coinbase, Binance, POS.DOG who already have full stake on 5-10-20 Validators. For 1KV Validators impossible to get into recommended, even if they have low fee ( I tested it by myself different ways).

**Now Polkadot preferences big multi validators , its not fit the initial idea of decentralization and dangerous for the Polkadot future:**
- if you have full nomination set, you are in favor to get more nominations on Dashboard, Polkadot.js/app and in every eco app
- if you have 5-10+ nodes you are more visible, it bring you more nominations 
- Dashboard recommend those who are already have full nomination and ignore who are in waiting list

We have 100M+ nominations in Polkadot recent months , my validator get 0 from this 100M nominations from dashboard or polkadot.js

So, official Polkadot Staking Dashboard supports multi-account validators. They make big ones even more bigger and steal from little independent validators who really provide quality service, unique locations and true decentralization! Its really bad!

It’s the random list recommended by Polkadot Dashboard 2/3 of this list are the validators that have 10+ Validators in Polkadot, already have full stake and getting bigger and bigger and open new and new nodes and dump earned tokens to the market. And Dashboard and Polkadot.js. supporting this policy by the design, by default. Why?

![d40a57dec02fcbcce3e6c0490e85c8ff3bb8fd17](https://github.com/w3f/1k-validators-be/assets/49550046/51b5f2de-e37a-48d2-b170-94aee8fd9b15)

**THE SOLUTION**

1.To add new category to section Nominate:
**1KV Validators**
**Participants of 1KV program. Choose to support the decentralization.**

2.In “Optimal selection” include at least 5 validators from 1KV Program for example who are in active set now, or other criteria, but including 1KV participants. There are 264 participants of the 1KV program and about 1000 total validators , I think its fair and long term effective to give 5 of 16 seats in every recommended validators list to 1KV participants.

3.In Polkadot.js/app [
](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.ibp.network%2Fpolkadot#/staking)
Not divide Validators on 2 classes - Active and Waiting , give all of them chance to get nominated by new Stakers, and give the ability to search both lists!
<img width="218" alt="Снимок экрана 2024-02-01 в 16 24 32" src="https://github.com/w3f/1k-validators-be/assets/49550046/6c17f464-c1b3-4335-b476-8c29a3de8307">

Discussions [here](https://forum.polkadot.network/t/polkadot-staking-dashboard-staking-polkadot-network-and-polkadot-js-not-supporting-decentralization-of-validators-by-design/5589/23)

**Comment by Noc2** [comment]
Hi. Thanks a lot for bringing this up. Once we ensure we can continue to run the program (with proper legal and technical setup), The full focus of the program is and will be to support the decentralization of the validator set. For example, we plan to significantly increase the number of funds behind it, which is partly why we are restructuring it in the first place. That said, I think a lot of the points you are raising here are valid to a certain degree but would be better suited as issues of the polkadotjs/apps repo and staking dashboard repo since the technical team here can not fix them.  Let me know if you have any other questions.

**Comment by michalisFr** [comment]
Hey @GlobalSG!

Thank you for your feedback. I appreciate how it is difficult for validators to grow their nominator base and your suggestions could help with that. 

However, this is an issue to be raised with the developers of the staking dashboard, as you've done in the forum discussion. We can't force such a feature, because the dashboard is not developed, nor controlled by W3F.

Similarly for Polkadot-JS UI, this is an issue to be raised in the [polkadot.js apps repo](https://github.com/polkadot-js/apps).

Rest assured that we are committed to the second point of decentralization. This is indeed the goal of 1KV and we'll do our best to help independent validators and decentralise the active set further.
